- name: creation of jenkins job
  hosts: localhost
  vars:
    jenkinns_username: "{{ lookup('aws_ssm', 'jenkins_username', region='us-east-1' ) }}"
    jenkins_password: "{{ lookup('aws_ssm', 'jenkins_password', region='us-east-1' ) }}"
    jenkinns_url: "{{ lookup('aws_ssm', 'jenkins_url', region='us-east-1' ) }}"
  tasks:
    - name: Create a jenkins job using basic authentication
      community.general.jenkins_job:
        config: "{{ lookup('template', 'job.xml') }}"
        name: frontend
        password: "{{jenkins_password}}"
        url: "{{jenkinns_url}}"
        user: "{{jenkinns_username}}"
      vars:
        repo_name: "frontend"

    - name: Create a jenkins job for backend
      community.general.jenkins_job:
        config: "{{ lookup('template', 'job.xml') }}"
        name: backend
        password: "{{jenkins_password}}"
        url: "{{jenkinns_url}}"
        user: "{{jenkinns_username}}"
      vars:
        repo_name: "backend"

    - name: Create a jenkins job for expense-parameters
      community.general.jenkins_job:
        config: "{{ lookup('template', 'job.xml') }}"
        name: expense-parameters
        password: "{{jenkins_password}}"
        url: "{{jenkinns_url}}"
        user: "{{jenkinns_username}}"
      vars:
        repo_name: "ssm-parameters-jenkins"

    - name: Create a jenkins job for expense-infra-creation-terraform
      community.general.jenkins_job:
        config: "{{ lookup('tempalte', 'job.xml') }}"
        name: expense-infra-creation-terraform
        password: "{{jenkins_password}}"
        url: "{{jenkinns_url}}"
        user: "{{jenkinns_username}}"
      vars:
        repo_name: "infra-creation-terraform"
    